//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for MessageRole.
const (
	Assistant MessageRole = "assistant"
	System    MessageRole = "system"
	User      MessageRole = "user"
)

// Valid indicates whether the value is a known member of the MessageRole enum.
func (e MessageRole) Valid() bool {
	switch e {
	case Assistant:
		return true
	case System:
		return true
	case User:
		return true
	default:
		return false
	}
}

// ChatCompletionRequest A real OpenAI `/v1/chat/completions` request (ADR-0012 v1 subset). Only
// `model`, `messages`, `stream`, `temperature`, `top_p`, `max_tokens` and
// `stop` are modeled and forwarded upstream; every other field is
// accepted-but-ignored via `additionalProperties: true` (liberal-accept).
type ChatCompletionRequest struct {
	// MaxTokens Optional upper bound on the completion length.
	MaxTokens *int `json:"max_tokens,omitempty"`

	// Messages The ordered chat history for the completion.
	Messages []Message `json:"messages"`

	// Model The upstream model to run the completion against.
	Model string `json:"model"`

	// Stop Optional stop sequences that end generation. Accepts a single
	// string or an array of strings, matching the OpenAI wire contract.
	Stop *ChatCompletionRequest_Stop `json:"stop,omitempty"`

	// Stream When true, the gateway responds with a `text/event-stream` (SSE)
	// body of `chat.completion.chunk` events terminated by `data: [DONE]`.
	Stream *bool `json:"stream,omitempty"`

	// Temperature Optional sampling temperature.
	Temperature *float32 `json:"temperature,omitempty"`

	// TopP Optional nucleus-sampling probability mass.
	TopP                 *float32               `json:"top_p,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ChatCompletionRequestStop0 defines model for .
type ChatCompletionRequestStop0 = string

// ChatCompletionRequestStop1 defines model for .
type ChatCompletionRequestStop1 = []string

// ChatCompletionRequest_Stop Optional stop sequences that end generation. Accepts a single
// string or an array of strings, matching the OpenAI wire contract.
type ChatCompletionRequest_Stop struct {
	union json.RawMessage
}

// ChatCompletionResponse A real OpenAI `chat.completion` object (ADR-0012). `id`, `object` and
// `created` are generated at the edge (not passed through from upstream);
// `system_fingerprint` is omitted.
type ChatCompletionResponse struct {
	// Choices The completion choices (always exactly one — index 0).
	Choices []Choice `json:"choices"`

	// Created Unix timestamp (seconds) when the gateway built the response.
	Created int64 `json:"created"`

	// Id An edge-generated completion id, prefixed "chatcmpl-".
	Id string `json:"id"`

	// Model The model that produced the completion.
	Model string `json:"model"`

	// Object Always "chat.completion".
	Object string `json:"object"`

	// Usage Token accounting for a completion (OpenAI shape). Aligned with the
	// canonical provider.Usage.
	Usage Usage `json:"usage"`
}

// Choice One chat.completion choice. The gateway always returns exactly one (index 0).
type Choice struct {
	// FinishReason The reason the completion ended (e.g. "stop", "length").
	FinishReason *string `json:"finish_reason"`

	// Index The choice index (always 0 — n>1 is a non-goal, CON-008).
	Index int `json:"index"`

	// Message The assistant message inside a chat.completion choice.
	Message ResponseMessage `json:"message"`
}

// Error The OpenAI error envelope `{ "error": { message, type, code } }` so
// unmodified OpenAI SDKs parse gateway and mapped-upstream errors
// (ADR-0012, FR-020).
type Error struct {
	// Error The OpenAI error object carried inside an Error envelope.
	Error ErrorDetail `json:"error"`
}

// ErrorDetail The OpenAI error object carried inside an Error envelope.
type ErrorDetail struct {
	// Code A short, machine-readable error code (may be null).
	Code *string `json:"code,omitempty"`

	// Message A human-readable description of the error.
	Message string `json:"message"`

	// Param The request parameter the error relates to, when applicable (may be null).
	Param *string `json:"param,omitempty"`

	// Type The OpenAI error type (e.g. "invalid_request_error", "server_error").
	Type string `json:"type"`
}

// HealthStatus Liveness probe response.
type HealthStatus struct {
	// Status Overall liveness status.
	Status string `json:"status"`
}

// Message One OpenAI chat message. `content` is a plain string (the v1 subset);
// multimodal/array content is a documented non-goal (ADR-0012, CON-008)
// and is rejected with an OpenAI-shaped 400 by the handler.
// `additionalProperties: true` so SDK-supplied extras (e.g. `name`) are
// accepted and ignored, never a 400 (liberal-accept).
type Message struct {
	// Content The message text.
	Content string `json:"content"`

	// Role The author of the message.
	Role                 MessageRole            `json:"role"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// MessageRole The author of the message.
type MessageRole string

// ReadinessStatus Readiness probe response with a per-dependency status map.
type ReadinessStatus struct {
	// Dependencies Per-dependency status; "ok" or an error description.
	Dependencies map[string]string `json:"dependencies"`

	// Status Overall readiness status.
	Status string `json:"status"`
}

// ResponseMessage The assistant message inside a chat.completion choice.
type ResponseMessage struct {
	// Content The assistant completion text.
	Content string `json:"content"`

	// Role Always "assistant" for a completion choice.
	Role string `json:"role"`
}

// Usage Token accounting for a completion (OpenAI shape). Aligned with the
// canonical provider.Usage.
type Usage struct {
	CompletionTokens int `json:"completion_tokens"`
	PromptTokens     int `json:"prompt_tokens"`
	TotalTokens      int `json:"total_tokens"`
}

// BadGateway The OpenAI error envelope `{ "error": { message, type, code } }` so
// unmodified OpenAI SDKs parse gateway and mapped-upstream errors
// (ADR-0012, FR-020).
type BadGateway = Error

// BadRequest The OpenAI error envelope `{ "error": { message, type, code } }` so
// unmodified OpenAI SDKs parse gateway and mapped-upstream errors
// (ADR-0012, FR-020).
type BadRequest = Error

// InternalServerError The OpenAI error envelope `{ "error": { message, type, code } }` so
// unmodified OpenAI SDKs parse gateway and mapped-upstream errors
// (ADR-0012, FR-020).
type InternalServerError = Error

// NotFound The OpenAI error envelope `{ "error": { message, type, code } }` so
// unmodified OpenAI SDKs parse gateway and mapped-upstream errors
// (ADR-0012, FR-020).
type NotFound = Error

// ServiceUnavailable The OpenAI error envelope `{ "error": { message, type, code } }` so
// unmodified OpenAI SDKs parse gateway and mapped-upstream errors
// (ADR-0012, FR-020).
type ServiceUnavailable = Error

// TooManyRequests The OpenAI error envelope `{ "error": { message, type, code } }` so
// unmodified OpenAI SDKs parse gateway and mapped-upstream errors
// (ADR-0012, FR-020).
type TooManyRequests = Error

// Unauthorized The OpenAI error envelope `{ "error": { message, type, code } }` so
// unmodified OpenAI SDKs parse gateway and mapped-upstream errors
// (ADR-0012, FR-020).
type Unauthorized = Error

// CreateChatCompletionJSONRequestBody defines body for CreateChatCompletion for application/json ContentType.
type CreateChatCompletionJSONRequestBody = ChatCompletionRequest

// Getter for additional properties for ChatCompletionRequest. Returns the specified
// element and whether it was found
func (a ChatCompletionRequest) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ChatCompletionRequest
func (a *ChatCompletionRequest) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ChatCompletionRequest to handle AdditionalProperties
func (a *ChatCompletionRequest) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["max_tokens"]; found {
		err = json.Unmarshal(raw, &a.MaxTokens)
		if err != nil {
			return fmt.Errorf("error reading 'max_tokens': %w", err)
		}
		delete(object, "max_tokens")
	}

	if raw, found := object["messages"]; found {
		err = json.Unmarshal(raw, &a.Messages)
		if err != nil {
			return fmt.Errorf("error reading 'messages': %w", err)
		}
		delete(object, "messages")
	}

	if raw, found := object["model"]; found {
		err = json.Unmarshal(raw, &a.Model)
		if err != nil {
			return fmt.Errorf("error reading 'model': %w", err)
		}
		delete(object, "model")
	}

	if raw, found := object["stop"]; found {
		err = json.Unmarshal(raw, &a.Stop)
		if err != nil {
			return fmt.Errorf("error reading 'stop': %w", err)
		}
		delete(object, "stop")
	}

	if raw, found := object["stream"]; found {
		err = json.Unmarshal(raw, &a.Stream)
		if err != nil {
			return fmt.Errorf("error reading 'stream': %w", err)
		}
		delete(object, "stream")
	}

	if raw, found := object["temperature"]; found {
		err = json.Unmarshal(raw, &a.Temperature)
		if err != nil {
			return fmt.Errorf("error reading 'temperature': %w", err)
		}
		delete(object, "temperature")
	}

	if raw, found := object["top_p"]; found {
		err = json.Unmarshal(raw, &a.TopP)
		if err != nil {
			return fmt.Errorf("error reading 'top_p': %w", err)
		}
		delete(object, "top_p")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ChatCompletionRequest to handle AdditionalProperties
func (a ChatCompletionRequest) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.MaxTokens != nil {
		object["max_tokens"], err = json.Marshal(a.MaxTokens)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'max_tokens': %w", err)
		}
	}

	if a.Messages != nil {
		object["messages"], err = json.Marshal(a.Messages)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'messages': %w", err)
		}
	}

	object["model"], err = json.Marshal(a.Model)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'model': %w", err)
	}

	if a.Stop != nil {
		object["stop"], err = json.Marshal(a.Stop)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'stop': %w", err)
		}
	}

	if a.Stream != nil {
		object["stream"], err = json.Marshal(a.Stream)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'stream': %w", err)
		}
	}

	if a.Temperature != nil {
		object["temperature"], err = json.Marshal(a.Temperature)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'temperature': %w", err)
		}
	}

	if a.TopP != nil {
		object["top_p"], err = json.Marshal(a.TopP)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'top_p': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Message. Returns the specified
// element and whether it was found
func (a Message) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Message
func (a *Message) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Message to handle AdditionalProperties
func (a *Message) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["content"]; found {
		err = json.Unmarshal(raw, &a.Content)
		if err != nil {
			return fmt.Errorf("error reading 'content': %w", err)
		}
		delete(object, "content")
	}

	if raw, found := object["role"]; found {
		err = json.Unmarshal(raw, &a.Role)
		if err != nil {
			return fmt.Errorf("error reading 'role': %w", err)
		}
		delete(object, "role")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Message to handle AdditionalProperties
func (a Message) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["content"], err = json.Marshal(a.Content)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'content': %w", err)
	}

	object["role"], err = json.Marshal(a.Role)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'role': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsChatCompletionRequestStop0 returns the union data inside the ChatCompletionRequest_Stop as a ChatCompletionRequestStop0
func (t ChatCompletionRequest_Stop) AsChatCompletionRequestStop0() (ChatCompletionRequestStop0, error) {
	var body ChatCompletionRequestStop0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChatCompletionRequestStop0 overwrites any union data inside the ChatCompletionRequest_Stop as the provided ChatCompletionRequestStop0
func (t *ChatCompletionRequest_Stop) FromChatCompletionRequestStop0(v ChatCompletionRequestStop0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeChatCompletionRequestStop0 performs a merge with any union data inside the ChatCompletionRequest_Stop, using the provided ChatCompletionRequestStop0
func (t *ChatCompletionRequest_Stop) MergeChatCompletionRequestStop0(v ChatCompletionRequestStop0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsChatCompletionRequestStop1 returns the union data inside the ChatCompletionRequest_Stop as a ChatCompletionRequestStop1
func (t ChatCompletionRequest_Stop) AsChatCompletionRequestStop1() (ChatCompletionRequestStop1, error) {
	var body ChatCompletionRequestStop1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChatCompletionRequestStop1 overwrites any union data inside the ChatCompletionRequest_Stop as the provided ChatCompletionRequestStop1
func (t *ChatCompletionRequest_Stop) FromChatCompletionRequestStop1(v ChatCompletionRequestStop1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeChatCompletionRequestStop1 performs a merge with any union data inside the ChatCompletionRequest_Stop, using the provided ChatCompletionRequestStop1
func (t *ChatCompletionRequest_Stop) MergeChatCompletionRequestStop1(v ChatCompletionRequestStop1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ChatCompletionRequest_Stop) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ChatCompletionRequest_Stop) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Liveness probe (FR-008)
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// Prometheus metrics exposition
	// (GET /metrics)
	GetMetrics(w http.ResponseWriter, r *http.Request)
	// Readiness probe (FR-009)
	// (GET /readyz)
	GetReadyz(w http.ResponseWriter, r *http.Request)
	// Create a chat completion
	// (POST /v1/chat/completions)
	CreateChatCompletion(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMetrics operation middleware
func (siw *ServerInterfaceWrapper) GetMetrics(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMetrics(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadyz operation middleware
func (siw *ServerInterfaceWrapper) GetReadyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateChatCompletion operation middleware
func (siw *ServerInterfaceWrapper) CreateChatCompletion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateChatCompletion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealthz)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/metrics", wrapper.GetMetrics)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/readyz", wrapper.GetReadyz)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/chat/completions", wrapper.CreateChatCompletion)

	return m
}

type BadGatewayJSONResponse Error

type BadRequestJSONResponse Error

type InternalServerErrorJSONResponse Error

type NotFoundJSONResponse Error

type ServiceUnavailableJSONResponse Error

type TooManyRequestsJSONResponse Error

type UnauthorizedJSONResponse Error

type GetHealthzRequestObject struct {
}

type GetHealthzResponseObject interface {
	VisitGetHealthzResponse(w http.ResponseWriter) error
}

type GetHealthz200JSONResponse HealthStatus

func (response GetHealthz200JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMetricsRequestObject struct {
}

type GetMetricsResponseObject interface {
	VisitGetMetricsResponse(w http.ResponseWriter) error
}

type GetMetrics200TextResponse string

func (response GetMetrics200TextResponse) VisitGetMetricsResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(response))
	return err
}

type GetReadyzRequestObject struct {
}

type GetReadyzResponseObject interface {
	VisitGetReadyzResponse(w http.ResponseWriter) error
}

type GetReadyz200JSONResponse ReadinessStatus

func (response GetReadyz200JSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadyz503JSONResponse ReadinessStatus

func (response GetReadyz503JSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type CreateChatCompletionRequestObject struct {
	Body *CreateChatCompletionJSONRequestBody
}

type CreateChatCompletionResponseObject interface {
	VisitCreateChatCompletionResponse(w http.ResponseWriter) error
}

type CreateChatCompletion200JSONResponse ChatCompletionResponse

func (response CreateChatCompletion200JSONResponse) VisitCreateChatCompletionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateChatCompletion200TexteventStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response CreateChatCompletion200TexteventStreamResponse) VisitCreateChatCompletionResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	flusher, ok := w.(http.Flusher)
	if !ok {
		// If w doesn't support flushing, fall back to io.Copy.
		_, err := io.Copy(w, response.Body)
		return err
	}
	// text/event-stream messages are typically small; use a
	// modest buffer and flush after each chunk so clients see
	// events immediately instead of waiting on OS buffering.
	buf := make([]byte, 4096)
	for {
		n, err := response.Body.Read(buf)
		if n > 0 {
			if _, writeErr := w.Write(buf[:n]); writeErr != nil {
				return writeErr
			}
			flusher.Flush()
		}
		if err != nil {
			if err == io.EOF {
				return nil
			}
			return err
		}
	}
}

type CreateChatCompletion400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateChatCompletion400JSONResponse) VisitCreateChatCompletionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateChatCompletion401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateChatCompletion401JSONResponse) VisitCreateChatCompletionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateChatCompletion404JSONResponse struct{ NotFoundJSONResponse }

func (response CreateChatCompletion404JSONResponse) VisitCreateChatCompletionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateChatCompletion429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response CreateChatCompletion429JSONResponse) VisitCreateChatCompletionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type CreateChatCompletion500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateChatCompletion500JSONResponse) VisitCreateChatCompletionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateChatCompletion502JSONResponse struct{ BadGatewayJSONResponse }

func (response CreateChatCompletion502JSONResponse) VisitCreateChatCompletionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type CreateChatCompletion503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response CreateChatCompletion503JSONResponse) VisitCreateChatCompletionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Liveness probe (FR-008)
	// (GET /healthz)
	GetHealthz(ctx context.Context, request GetHealthzRequestObject) (GetHealthzResponseObject, error)
	// Prometheus metrics exposition
	// (GET /metrics)
	GetMetrics(ctx context.Context, request GetMetricsRequestObject) (GetMetricsResponseObject, error)
	// Readiness probe (FR-009)
	// (GET /readyz)
	GetReadyz(ctx context.Context, request GetReadyzRequestObject) (GetReadyzResponseObject, error)
	// Create a chat completion
	// (POST /v1/chat/completions)
	CreateChatCompletion(ctx context.Context, request CreateChatCompletionRequestObject) (CreateChatCompletionResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealthz operation middleware
func (sh *strictHandler) GetHealthz(w http.ResponseWriter, r *http.Request) {
	var request GetHealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthz(ctx, request.(GetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthzResponseObject); ok {
		if err := validResponse.VisitGetHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMetrics operation middleware
func (sh *strictHandler) GetMetrics(w http.ResponseWriter, r *http.Request) {
	var request GetMetricsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMetrics(ctx, request.(GetMetricsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMetrics")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMetricsResponseObject); ok {
		if err := validResponse.VisitGetMetricsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadyz operation middleware
func (sh *strictHandler) GetReadyz(w http.ResponseWriter, r *http.Request) {
	var request GetReadyzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadyz(ctx, request.(GetReadyzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadyz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadyzResponseObject); ok {
		if err := validResponse.VisitGetReadyzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateChatCompletion operation middleware
func (sh *strictHandler) CreateChatCompletion(w http.ResponseWriter, r *http.Request) {
	var request CreateChatCompletionRequestObject

	var body CreateChatCompletionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateChatCompletion(ctx, request.(CreateChatCompletionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateChatCompletion")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateChatCompletionResponseObject); ok {
		if err := validResponse.VisitCreateChatCompletionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"vFpvc9s20v8qO3yeF1IqyYqT3rTOKzdJm9w1sSdO5l6UGRMiVyIaEOABoG0145l+iPsM98H6SW52AZL6",
	"Q9nOXJtXtiRisdj97e5vF/yc5KaqjUbtXXLyObHoaqMd8ocfRPGT8Hgt1vQpN9qj9vSvqGslc+Gl0Ue/",
	"OqPpO5eXWAn67/8tLpOT5P+OetFH4Vd39NJaY5Pb29tJUqDLraxJSHKSvC8Rmtp5i6KC2porWaAFi76x",
	"GgsQGqS+EkoW0Ko4S24npOI7/FeDzn8dFW3YDK6Fg0qopbEVFmAsLIVUWACryLuyeq+1R6uFukB7hTZI",
	"/sv1PNXQaLypMfdYgOOtAelpMHneWIsFK/fW+B9No4uvajlkB5rG5ggjnK1mUJkC1Zgtqo2HJanE+pHR",
	"ZI4ftLgSUomFwq+j6SpgnrwqdA/KAmvUBep8DdIB21F7tYam14/Vfm/MG6HXEZbu6+icK4naQykcLBA1",
	"WOERlKykj87+oEXjS2Plb1h8/VAhx/b7zxJaEYXQHs9L4Z+bqlZI6zcCWhSFpK+EOremRuslZSZvG9wD",
	"PVgUCs5q1KevITu6enyUl8Kz1kGsyzqVRqcv3k3n88fHcPUYXLNw6MczONNqneqM8ZhNIKvQObFCR/8H",
	"DNB/HqsarfCNRf5o6suanxY3l958QtpH6CLVmfOmzkBYDBDnLFbA0thrYQssOmQ9A7xCuwbjS7SwlKgK",
	"kC7VIs+x9lhMF42fypU2lhKMFJANmeUEyCwZjJRcoBVqGpaPZ6lOJkm9Yb7PSa8rfdo25FkdJENT12hh",
	"QeEIRoMnlHXGBIV65ctZMkn8usbkJJHa4wotYa013L5wwoWxBdJJyD1QSueNXZNVdnYg0dJj5e4D4Zuw",
	"G20cVRHWijUrQnYf1qILa34GvAHb7B1SrITUzm+c0nkr9Ypkk3fvsB79DI7wpnN04OmwqAtYoSb00AHh",
	"lD3kQICTeqUw1UF8zDx8DDBLCN+6CVTC5yU9QHpGqF9LSzprb0Xug7N1o2K6DJFiNJ4tk5NfPu+d4nNv",
	"4r0DbhvzIx+ZLBYOvRSN8snJUii3F4v/LFEzGiesaJtPQ+EuHFxLX4KgULrxR3iF2k9jfMHo4uLlONUL",
	"U/DJMwLJbAMUednoTxnwIgcebSW1oKKyWENWCC9O4JcXZ29ffsyCKeIhFsYoFJqP1cfvXe4TVa3Y0v3j",
	"GzDQTbUIWOf4v0OQbnKFjZt2AmtrFmIhlfRrqIRzA1JvJwllKmkpVf8SUbwRVh+7FWbxK+ae9NhNoYEj",
	"7Su2kyd37JtBkNhnyPEMMllQggu/tMktt0h2D/ktgpoynGeXY7FCGFHWr4VzWIAvrWlWJSytqbrYGz+j",
	"LLl2HqvLpdQrtLWV2mdUX00lPdWugeyVl0bmh7LLRvTG52Ak1LVYO8AbkVPBNhrhj9//DVIXeAPz8YMz",
	"zXMWOJRoojX2Vfqg5Q14WaHzoqph5DCnEBjDNcfIRnQsGqmC8XqCO0mIYAof0uvfng5mWzmw7almF0x7",
	"x2zYRRYTqC0u5Q0WkCYEgbyq1TRNBhPdHUk05k7KbbU1RZOzp3ez+J7EiNp9rYOfgkobqDygWMNp/x6f",
	"fQi1YSekZJF0avTem3Sh1kKs3WQ44hgN+6GvEXYOEKE4g016GVEZWpxtdI42obkN/qXU0pWXFkVkakPE",
	"i37brWXEXYtIuVOuXmkygTQJhTxNeK/dyrFnc1bsQOTxGWNUtTE350jTaTOfP8HHFNgCtNHTlRFqAs/P",
	"3k7n8+/Gd9KI+zzc5rqOB+z6mlXuxU12bDjk265T2z9mzJyhn0J9hcrUCNlnSBP+Lk1O4DPEzSZAoieQ",
	"mwLhFm4zcCbVja5MIZcSi1baxYt/OKiFdRvw0AVUoq6xmHZchTdwqe6y8wR+fDedH88HWR62h7iXwr9A",
	"L6Tas1wQcNA+cdX9Voo1JRfW0pmldrJAYjgvt4y4D3Yy21AJc6WxnugQsSGcWhQFoTZux8YeVZRTEQjR",
	"D4P2Btx29yubSuh+m42fiaRwwaOdB7NULWzLmQ51SPwIerS9KLCohCfiaCahVsQujfb/8rOFL+51FD3W",
	"pYg4b7mMWl5GdFPOCDOF9pvxwLl3KUwXe/zcEKReoVC+vPDCNwOl/Wd5hRqdY/q0XSK3IeMOCDi7oqZI",
	"gWoFhQfvVz0KHFL5TY+YhzeqVB6i0bkDiqaZQRZb8ixkyVoJqSP1hxEBo+9Vn6W6apSXlSmEOgp9Qlwd",
	"FhcmbyrUVPjbbAsbSaPNu6mmLCOpCP0apkWBmuuo4dSVosYCns7nRLBJiVLoQqGdpfrOLtQZymlT1xBq",
	"sQC88Va4iK1MiwqzMVHHvsvlhBe73AloaolB8M4P6Wg3xhkDNCWYGKjfGIxRa9SB8AhDizbKW18lkwR1",
	"UzE8mL4yUUCbTBLhnHReaL+BmAPI4l0nnepDCHuHopAE10Nx0T2wExhtj1WjnW4MrgKYqa7sR073WPw8",
	"DOmBRnFbo/OhHZ9BmphPaRI725BtNtZteKU//H2hbLuzf2EsT7bPOmz4bVIxDI7W1x3C2tJ2iAB+GW57",
	"+RuSvhDEHafuhKUJT1sEDKr3P0P2wwF7mU9UxPLcNNpTStvTYRSzIuec8QxOlVzpNiX5ElOdC220zIXq",
	"LghmvNtwQmgFb0y69jlmbU1V+zsf8cYLdccTOybaljgZUGRH5L4Rb5loL82+Fc+bhZI5vHr//hxOz193",
	"YzOnGuLeP//8puWPs1Sn+n0pHbgac7mMA15K9ryAB04QB/GU3mzjy07e1lCp55uPJ92X06W0zo9nEK42",
	"mDo4zuHcwpqGnczTQ2HXIdX33SiPAaQPvs2MqOWUWNsKdQZXxzDKnC+mpff1NFCNDL6BMJh1GXzDs1Ur",
	"c9/+Op7Bq1CXHEgyN9W+0F13W2YXvCSoy/cyS5FjFkpgJWp63CHUwcIv3p8R9zpiRbmTarGX6qxDX5xU",
	"Z0dZmy8yHtDSAqE9HcraJhBFJdZo2yI8/34cHRRnJa5G8Sm45tGjB0yy2UFhOPDo0VZD0LMEKsIHWg06",
	"c5Y3VmXUd5JcB9fGfkp1HHm2iBLMJqypp1KH9rUlraGBIDw9erRdoFmhu9jB+AQa/Umb65ZnhKG3I78j",
	"8rCJqmk2YVujQ53jZY1aKL+mH5c2zFXXm18qs5L+ciEFz+vbOngZbMSidHyMKiU99Mfv/2EOAlsUxEkV",
	"7nV2uEj2dD5vh4rSK06SwUZtx3Z6/jqZJFdoXQjW49l8Nud5B6lZy+QkeTKbz55QrhK+5GRyVDLt/Y3+",
	"X6EfKvBhPHA8n5MzlNEr+ktAqa3JqfoR4yNaS+nb1HG6/LpITpKf0L+K8ifbV7vH8/mfdgu0xdwPXAbt",
	"68pXQE1VCbve5/cjamvn3435qaMKKXTdQRudW1OhL7FxXB0Bb2rjGHwxRGbwoifEJYbQaWsP7/ss1WRS",
	"njtLF8k3CyNMaOPDrIsvcSgk/n5x9jaGQMDEnuHfRKXvNTxPwXnDbZPvVuJ9ptUfO1oIWqX3LbBj74G1",
	"/ZpgdaJX64cBkxvUcIllcSWd5wue7QvTAPT1hCjgt/MnvCbVwoNC4TyPvbYXFOY6phz2SpgeuD1Om+qe",
	"1NL5F8aXkAuH7oBj3oVz/YUBscvah+7olYJNEsp5KJqI72u/nT/5qvrc44cd+Oy2HSFev4/xOlCxSMXa",
	"uCEcNdpFwjxw9caJbueuzqEKzepiHUlBxsWUr53am1rSPOPbqSx0z/HKarxzJRVA3N/AcWBnw7cpGYyO",
	"5/Pxgc1C43vHhVeqh2+8mJFML4iyvOR7rXHMQ9p5FEXbfJJmqW47e1igMtezUEDPX8OT2Zw4Cr9B0Si1",
	"pnC25CCh4eLiZdcYTngCabQK7bw2OmpCdM01OWdppuB0qC7pUdJ8xitIGLGPVC+wFFfSNJae7GhXLKM+",
	"vOshNTw/ffdiOp8/HQrH5zx537Z2Evg0Ov+DKf68N4+G3zG43abv5MPbvzAzHLilu+V7yR1obEvdDpp9",
	"zEAMEbPcjKIClRcORq0PBkd1wy+UbMfjDH40tsX7SYyrzYopIj4Phc62gD5WuvWHouPi5bi7R4eRQ4QO",
	"QpsThGep7g+Z8k3v0+C4IX90Dj7aeIGMlzy+f8nWqzS86On9i7qXrWjB8ff3L9h9jYhrwgMONPTKGa89",
	"fpAx2hf++hJ095KBl7S2S0UI8f0MH4AXGjjHLyccfhOLqQk6YNocRuPyCsEbkN6BIsKhQRQFJTxCeGNV",
	"cpIcJbcfb/8bAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
