//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for MessageRole.
const (
	Assistant MessageRole = "assistant"
	System    MessageRole = "system"
	User      MessageRole = "user"
)

// Valid indicates whether the value is a known member of the MessageRole enum.
func (e MessageRole) Valid() bool {
	switch e {
	case Assistant:
		return true
	case System:
		return true
	case User:
		return true
	default:
		return false
	}
}

// ChatCompletionRequest A chat completion request. Aligned with the canonical provider.Request
// shape (mapped via the ACL in CARD-003).
type ChatCompletionRequest struct {
	// MaxTokens Optional upper bound on the completion length.
	MaxTokens *int `json:"max_tokens,omitempty"`

	// Messages The ordered chat history for the completion.
	Messages []Message `json:"messages"`

	// Model The upstream model to run the completion against.
	Model string `json:"model"`

	// Stream When true, the gateway responds with a `text/event-stream` (SSE)
	// body instead of a JSON response (CARD-004).
	Stream *bool `json:"stream,omitempty"`

	// Temperature Optional sampling temperature.
	Temperature *float32 `json:"temperature,omitempty"`
}

// ChatCompletionResponse A chat completion result. Aligned with the canonical provider.Response.
type ChatCompletionResponse struct {
	// Content The assistant completion text.
	Content string `json:"content"`

	// FinishReason The canonical reason the completion ended (e.g. "stop", "length").
	FinishReason string `json:"finish_reason"`

	// Model The model that produced the completion.
	Model string `json:"model"`

	// Usage Token accounting for a completion. Aligned with the canonical
	// provider.Usage.
	Usage Usage `json:"usage"`
}

// Error A structured JSON error body.
type Error struct {
	// Error A short, machine-readable error code.
	Error string `json:"error"`

	// Message A human-readable description of the error.
	Message string `json:"message"`
}

// HealthStatus Liveness probe response.
type HealthStatus struct {
	// Status Overall liveness status.
	Status string `json:"status"`
}

// Message One chat message. Aligned with the canonical provider.Message.
type Message struct {
	// Content The message text.
	Content string `json:"content"`

	// Role The author of the message.
	Role MessageRole `json:"role"`
}

// MessageRole The author of the message.
type MessageRole string

// ReadinessStatus Readiness probe response with a per-dependency status map.
type ReadinessStatus struct {
	// Dependencies Per-dependency status; "ok" or an error description.
	Dependencies map[string]string `json:"dependencies"`

	// Status Overall readiness status.
	Status string `json:"status"`
}

// Usage Token accounting for a completion. Aligned with the canonical
// provider.Usage.
type Usage struct {
	CompletionTokens int `json:"completion_tokens"`
	PromptTokens     int `json:"prompt_tokens"`
	TotalTokens      int `json:"total_tokens"`
}

// BadGateway A structured JSON error body.
type BadGateway = Error

// BadRequest A structured JSON error body.
type BadRequest = Error

// InternalServerError A structured JSON error body.
type InternalServerError = Error

// NotFound A structured JSON error body.
type NotFound = Error

// ServiceUnavailable A structured JSON error body.
type ServiceUnavailable = Error

// TooManyRequests A structured JSON error body.
type TooManyRequests = Error

// CreateChatCompletionJSONRequestBody defines body for CreateChatCompletion for application/json ContentType.
type CreateChatCompletionJSONRequestBody = ChatCompletionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Liveness probe (FR-008)
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// Prometheus metrics exposition
	// (GET /metrics)
	GetMetrics(w http.ResponseWriter, r *http.Request)
	// Readiness probe (FR-009)
	// (GET /readyz)
	GetReadyz(w http.ResponseWriter, r *http.Request)
	// Create a chat completion
	// (POST /v1/chat/completions)
	CreateChatCompletion(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMetrics operation middleware
func (siw *ServerInterfaceWrapper) GetMetrics(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMetrics(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadyz operation middleware
func (siw *ServerInterfaceWrapper) GetReadyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateChatCompletion operation middleware
func (siw *ServerInterfaceWrapper) CreateChatCompletion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateChatCompletion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealthz)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/metrics", wrapper.GetMetrics)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/readyz", wrapper.GetReadyz)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/chat/completions", wrapper.CreateChatCompletion)

	return m
}

type BadGatewayJSONResponse Error

type BadRequestJSONResponse Error

type InternalServerErrorJSONResponse Error

type NotFoundJSONResponse Error

type ServiceUnavailableJSONResponse Error

type TooManyRequestsJSONResponse Error

type GetHealthzRequestObject struct {
}

type GetHealthzResponseObject interface {
	VisitGetHealthzResponse(w http.ResponseWriter) error
}

type GetHealthz200JSONResponse HealthStatus

func (response GetHealthz200JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMetricsRequestObject struct {
}

type GetMetricsResponseObject interface {
	VisitGetMetricsResponse(w http.ResponseWriter) error
}

type GetMetrics200TextResponse string

func (response GetMetrics200TextResponse) VisitGetMetricsResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(response))
	return err
}

type GetReadyzRequestObject struct {
}

type GetReadyzResponseObject interface {
	VisitGetReadyzResponse(w http.ResponseWriter) error
}

type GetReadyz200JSONResponse ReadinessStatus

func (response GetReadyz200JSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadyz503JSONResponse ReadinessStatus

func (response GetReadyz503JSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type CreateChatCompletionRequestObject struct {
	Body *CreateChatCompletionJSONRequestBody
}

type CreateChatCompletionResponseObject interface {
	VisitCreateChatCompletionResponse(w http.ResponseWriter) error
}

type CreateChatCompletion200JSONResponse ChatCompletionResponse

func (response CreateChatCompletion200JSONResponse) VisitCreateChatCompletionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateChatCompletion200TexteventStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response CreateChatCompletion200TexteventStreamResponse) VisitCreateChatCompletionResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	flusher, ok := w.(http.Flusher)
	if !ok {
		// If w doesn't support flushing, fall back to io.Copy.
		_, err := io.Copy(w, response.Body)
		return err
	}
	// text/event-stream messages are typically small; use a
	// modest buffer and flush after each chunk so clients see
	// events immediately instead of waiting on OS buffering.
	buf := make([]byte, 4096)
	for {
		n, err := response.Body.Read(buf)
		if n > 0 {
			if _, writeErr := w.Write(buf[:n]); writeErr != nil {
				return writeErr
			}
			flusher.Flush()
		}
		if err != nil {
			if err == io.EOF {
				return nil
			}
			return err
		}
	}
}

type CreateChatCompletion400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateChatCompletion400JSONResponse) VisitCreateChatCompletionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateChatCompletion404JSONResponse struct{ NotFoundJSONResponse }

func (response CreateChatCompletion404JSONResponse) VisitCreateChatCompletionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateChatCompletion429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response CreateChatCompletion429JSONResponse) VisitCreateChatCompletionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type CreateChatCompletion500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateChatCompletion500JSONResponse) VisitCreateChatCompletionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateChatCompletion502JSONResponse struct{ BadGatewayJSONResponse }

func (response CreateChatCompletion502JSONResponse) VisitCreateChatCompletionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type CreateChatCompletion503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response CreateChatCompletion503JSONResponse) VisitCreateChatCompletionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Liveness probe (FR-008)
	// (GET /healthz)
	GetHealthz(ctx context.Context, request GetHealthzRequestObject) (GetHealthzResponseObject, error)
	// Prometheus metrics exposition
	// (GET /metrics)
	GetMetrics(ctx context.Context, request GetMetricsRequestObject) (GetMetricsResponseObject, error)
	// Readiness probe (FR-009)
	// (GET /readyz)
	GetReadyz(ctx context.Context, request GetReadyzRequestObject) (GetReadyzResponseObject, error)
	// Create a chat completion
	// (POST /v1/chat/completions)
	CreateChatCompletion(ctx context.Context, request CreateChatCompletionRequestObject) (CreateChatCompletionResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealthz operation middleware
func (sh *strictHandler) GetHealthz(w http.ResponseWriter, r *http.Request) {
	var request GetHealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthz(ctx, request.(GetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthzResponseObject); ok {
		if err := validResponse.VisitGetHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMetrics operation middleware
func (sh *strictHandler) GetMetrics(w http.ResponseWriter, r *http.Request) {
	var request GetMetricsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMetrics(ctx, request.(GetMetricsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMetrics")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMetricsResponseObject); ok {
		if err := validResponse.VisitGetMetricsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadyz operation middleware
func (sh *strictHandler) GetReadyz(w http.ResponseWriter, r *http.Request) {
	var request GetReadyzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadyz(ctx, request.(GetReadyzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadyz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadyzResponseObject); ok {
		if err := validResponse.VisitGetReadyzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateChatCompletion operation middleware
func (sh *strictHandler) CreateChatCompletion(w http.ResponseWriter, r *http.Request) {
	var request CreateChatCompletionRequestObject

	var body CreateChatCompletionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateChatCompletion(ctx, request.(CreateChatCompletionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateChatCompletion")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateChatCompletionResponseObject); ok {
		if err := validResponse.VisitCreateChatCompletionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"vFlRc9s2Ev4rO7x7sKaypNjpzFV5cpO0yU1Se2xn7qHsVCtyJaIFFzwAlKPL6L/fLEBREkXZ7kyTp8gR",
	"sFh8+327i9WXJDNlZZjYu2T6JbHkKsOOwh8/Yv4zenrAtfyVGfbEXj5iVWmVoVeGx384w/J/LiuoRPn0",
	"T0uLZJr8Y7wzPY7fuvFba41NNpvNMMnJZVZVYiSZJvcFQV05bwlLqKxZqZwsWPK1ZcoBGRSvUKscti6O",
	"ks1QXLyl/9bk/Ldx0cbD4AEdlKgXxpaUg7GwQKUph+BiODW49549WUZ9R3ZFNlr+6n5eMdRMnyvKPOXg",
	"wtFAshpMltXWUh6c+8X4n0zN+TdFjkIATW0zgjMaLUdQmpz0ICDKxsNCXAr+CWgqo0+MK1Qa55q+jafL",
	"yHmJKvKOlDlVxDlxtgblIODIXq+h3vkX3L435iPyuqGl+zY+Z1oReyjQwZyIwaIn0KpUPgR7M2wOCe68",
	"LtC/NmWlSSzs6afDI8gK9JC1K7cxHMGVVkuR5YPyBXg5H9mwylC32h01dlN2BVYEZyVWlShEYdhx9foD",
	"KIbXV7dvzieTy8Eo5WSYVNZUZL2KCajEz7978yexO/buOnxADXVVkYW50AYMR292LmvipS9GyTDx64qS",
	"aaLY05KsRKok53BJPcYFUmNzspRHEArlvLFrWBjbOUFMK0+leyp+H+NpcnDjClqL6+CISKDfi5Z+YQ14",
	"A7Y+uiQuUbHze7d03ipeiu24PRpfYK19Ml2gdtRl0X8KYvC2pmGwvhVBzLa5i6FGmHn67Me0Ivbn0fQM",
	"zu7u3g5Snpt8DeIHYQ5mAQj/vrv+pc3XcNbE+mUT68bVuTGakAMuVFZk0deWHgm4w7LSipewt3zv6lyX",
	"c4nvZpgIX5WlPJn+2mC8F/Tf2h1m/gdlXhzoKiN6/jxpuFo/WxlNBeuh/F6qOCYDOqecRz44WQLSG/mF",
	"YuWK3y1hk2d60kbrXFzVJZYkvLzJ02nivKnSZAhpElWVJoPegx+hc8NiAa+yJq8zynv0dGSxDsp5QmCf",
	"orxOxH0LbBeXrfE+OrQFuxt9522dCe/yyPFYXUUAo6OI0kkjhbF+CCVmhWI6t4S5FJHGWGZy6ke3ySM9",
	"Fou6RN4Z2vta9Cg4B9s9ZjugRZ93Z/WB845Q++LOo697MugHtSIm5yTMc9pr2rrwuBMGrldkUWvQW0Nx",
	"4dO+Nwb7XP54Crprpqjo5sLP03FjbvTXRNwccVq31mg6of/aF9LFxViWu+OJ6zLcfe08lYHTJPFrE8Ye",
	"HCdgC6fuZNIH3y1hriQWp4LeLuhEfVs8KrLne21UjBSUWB1D2C5r/sY8VzH/3xysO0Lv0KObvhNfQZqY",
	"P9Ok6fCi3vb27UVld/mneGrbu/9Fog4P79oH/Kd+1t5LawSYZaZmLwVRuhPcz6WP0DjllsfBfH8x2lra",
	"a8OO+6jKmrLyjy7xxqN+ZEUHmkOLwx5HOiaPUROTihfmGLabeq5VBu/u72/g6uZ929M5XauM4MOHj9vu",
	"Z5RyyveFcuAqytSiadyl/w8bFC81QfOaEVXa2hetvQdlpbCxt5j5lM+u3tyeTyYvXgzb/zxfKOv8YATx",
	"fQhyBQfIsSZaU4eohtYW7RrQUspLYul5KIeFNSUoH2M7M1ipcykaS+IZrC7gbOZ8fl54X53HN+AMvoNZ",
	"KIduBt+lPBNeZn777WAE75BzTda1rdrlAJQgX8rjIrSF29NTnt2F7dH18NBdYEaz4H6JlSx3BFUE+839",
	"tQNvxsHnDg9n3SfDbDzbtkiz9r2A7OV+1taxoGlck4UG1MkP255SeR0kF2O57WKvbt4nw2RF1kUKvBhN",
	"RhPhpamIsVLJNLkcTUaXogD0RaDouAgF7n/yeUm+L9v52rKDi8kE0IE2vJR/xdnKmkxSgXKAUsAkGZjQ",
	"qyrD7/NkmvxM/l1jf3g4dbmYTP62N+NBjT7xdDz2NTwX67JEuz6u5Gc/CeD/GoRV45KEBO4kRjfWlOQL",
	"ql2od0CfK+NCIheZlOhH8MZktfCLcijIUpBPo/dw7quUBdL4unBQaVSx6Q1MY+NjU6kpF/SbR0cEIHLi",
	"CPiPjdNPAh/eOuHAQ8i7ef247Oyu3SAEW6ePEejg3bN3tyeiLrVm/TxiPsizjlZk5Sm3VM6HN+3hLCMS",
	"fT2Uevj95DLsSRk9aELnwTB1NuTmgUdwv41KhtYqSVydAp/yrsLL/efGF5ChI3ciMLfxXl9REN0Wpm98",
	"pjXsV2RJu1uIwoDn+8nlN/XniTh06NPtwaJef2j0unoxlj53vCuoAeLK9A2AbmuWoHafus20ISS6znjC",
	"kY5Tx/m6KTWzUEPDcGG2nRcoB7Mwg5jBmRhpBhODzuAhkhibMptyEPas/4k+g7OLyWRw4jBva5o9NtZI",
	"uX+uEWrb+Z1Uv7fylRtAd8ohVsWzlPMmkcGctHkYwXVFLP3F5Wgi5S4MN2ut1yJnKwFChru7t22XPARn",
	"Ujas18EoG248kSbA1VnI0nGYptwu6UnSfBV2iDFpOlKeU4ErZWorK9sKHuboOfg4ht0N3172yfG1JfR0",
	"iHYSuzRy/keT/30/CvTPIzeHTaHEcPMVM8OJ0c8mjKU61Di0eiiaY85AIxGz2FdRTtqj2x+K9TwY+me9",
	"h3ocwU/Gbvk+bXS1XzGx4ecp6Rwa2Gml3X9KHXdvB+AkWpwRnDkiaCm0/5x6lfLB5G8zTF7GwPXFow3w",
	"eO+3nbDl5dNb2p80ZMPFD09v6A7rQ3p/hm99P+yEvRfPutf2Z7VdNXl8S89PIYdZP6r1OFlHDsUO3yXT",
	"X7888ntH6DLIQeiAwZJGr1YE3oDyDrT0DgyY55K7hKy11ck0GSeb3zb/DwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
