//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for MessageRole.
const (
	Assistant MessageRole = "assistant"
	System    MessageRole = "system"
	User      MessageRole = "user"
)

// Valid indicates whether the value is a known member of the MessageRole enum.
func (e MessageRole) Valid() bool {
	switch e {
	case Assistant:
		return true
	case System:
		return true
	case User:
		return true
	default:
		return false
	}
}

// ChatCompletionRequest A real OpenAI `/v1/chat/completions` request (ADR-0012 v1 subset). Only
// `model`, `messages`, `stream`, `temperature`, `top_p`, `max_tokens` and
// `stop` are modeled and forwarded upstream; every other field is
// accepted-but-ignored via `additionalProperties: true` (liberal-accept).
type ChatCompletionRequest struct {
	// MaxTokens Optional upper bound on the completion length.
	MaxTokens *int `json:"max_tokens,omitempty"`

	// Messages The ordered chat history for the completion.
	Messages []Message `json:"messages"`

	// Model The upstream model to run the completion against.
	Model string `json:"model"`

	// Stop Optional stop sequences that end generation.
	Stop *[]string `json:"stop,omitempty"`

	// Stream When true, the gateway responds with a `text/event-stream` (SSE)
	// body of `chat.completion.chunk` events terminated by `data: [DONE]`.
	Stream *bool `json:"stream,omitempty"`

	// Temperature Optional sampling temperature.
	Temperature *float32 `json:"temperature,omitempty"`

	// TopP Optional nucleus-sampling probability mass.
	TopP                 *float32               `json:"top_p,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ChatCompletionResponse A real OpenAI `chat.completion` object (ADR-0012). `id`, `object` and
// `created` are generated at the edge (not passed through from upstream);
// `system_fingerprint` is omitted.
type ChatCompletionResponse struct {
	// Choices The completion choices (always exactly one — index 0).
	Choices []Choice `json:"choices"`

	// Created Unix timestamp (seconds) when the gateway built the response.
	Created int64 `json:"created"`

	// Id An edge-generated completion id, prefixed "chatcmpl-".
	Id string `json:"id"`

	// Model The model that produced the completion.
	Model string `json:"model"`

	// Object Always "chat.completion".
	Object string `json:"object"`

	// Usage Token accounting for a completion (OpenAI shape). Aligned with the
	// canonical provider.Usage.
	Usage Usage `json:"usage"`
}

// Choice One chat.completion choice. The gateway always returns exactly one (index 0).
type Choice struct {
	// FinishReason The reason the completion ended (e.g. "stop", "length").
	FinishReason *string `json:"finish_reason"`

	// Index The choice index (always 0 — n>1 is a non-goal, CON-008).
	Index int `json:"index"`

	// Message The assistant message inside a chat.completion choice.
	Message ResponseMessage `json:"message"`
}

// Error The OpenAI error envelope `{ "error": { message, type, code } }` so
// unmodified OpenAI SDKs parse gateway and mapped-upstream errors
// (ADR-0012, FR-020).
type Error struct {
	// Error The OpenAI error object carried inside an Error envelope.
	Error ErrorDetail `json:"error"`
}

// ErrorDetail The OpenAI error object carried inside an Error envelope.
type ErrorDetail struct {
	// Code A short, machine-readable error code (may be null).
	Code *string `json:"code,omitempty"`

	// Message A human-readable description of the error.
	Message string `json:"message"`

	// Param The request parameter the error relates to, when applicable (may be null).
	Param *string `json:"param,omitempty"`

	// Type The OpenAI error type (e.g. "invalid_request_error", "server_error").
	Type string `json:"type"`
}

// HealthStatus Liveness probe response.
type HealthStatus struct {
	// Status Overall liveness status.
	Status string `json:"status"`
}

// Message One OpenAI chat message. `content` is a plain string (the v1 subset);
// multimodal/array content is a documented non-goal (ADR-0012, CON-008)
// and is rejected with an OpenAI-shaped 400 by the handler.
// `additionalProperties: true` so SDK-supplied extras (e.g. `name`) are
// accepted and ignored, never a 400 (liberal-accept).
type Message struct {
	// Content The message text.
	Content string `json:"content"`

	// Role The author of the message.
	Role                 MessageRole            `json:"role"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// MessageRole The author of the message.
type MessageRole string

// ReadinessStatus Readiness probe response with a per-dependency status map.
type ReadinessStatus struct {
	// Dependencies Per-dependency status; "ok" or an error description.
	Dependencies map[string]string `json:"dependencies"`

	// Status Overall readiness status.
	Status string `json:"status"`
}

// ResponseMessage The assistant message inside a chat.completion choice.
type ResponseMessage struct {
	// Content The assistant completion text.
	Content string `json:"content"`

	// Role Always "assistant" for a completion choice.
	Role string `json:"role"`
}

// Usage Token accounting for a completion (OpenAI shape). Aligned with the
// canonical provider.Usage.
type Usage struct {
	CompletionTokens int `json:"completion_tokens"`
	PromptTokens     int `json:"prompt_tokens"`
	TotalTokens      int `json:"total_tokens"`
}

// BadGateway The OpenAI error envelope `{ "error": { message, type, code } }` so
// unmodified OpenAI SDKs parse gateway and mapped-upstream errors
// (ADR-0012, FR-020).
type BadGateway = Error

// BadRequest The OpenAI error envelope `{ "error": { message, type, code } }` so
// unmodified OpenAI SDKs parse gateway and mapped-upstream errors
// (ADR-0012, FR-020).
type BadRequest = Error

// InternalServerError The OpenAI error envelope `{ "error": { message, type, code } }` so
// unmodified OpenAI SDKs parse gateway and mapped-upstream errors
// (ADR-0012, FR-020).
type InternalServerError = Error

// NotFound The OpenAI error envelope `{ "error": { message, type, code } }` so
// unmodified OpenAI SDKs parse gateway and mapped-upstream errors
// (ADR-0012, FR-020).
type NotFound = Error

// ServiceUnavailable The OpenAI error envelope `{ "error": { message, type, code } }` so
// unmodified OpenAI SDKs parse gateway and mapped-upstream errors
// (ADR-0012, FR-020).
type ServiceUnavailable = Error

// TooManyRequests The OpenAI error envelope `{ "error": { message, type, code } }` so
// unmodified OpenAI SDKs parse gateway and mapped-upstream errors
// (ADR-0012, FR-020).
type TooManyRequests = Error

// Unauthorized The OpenAI error envelope `{ "error": { message, type, code } }` so
// unmodified OpenAI SDKs parse gateway and mapped-upstream errors
// (ADR-0012, FR-020).
type Unauthorized = Error

// CreateChatCompletionJSONRequestBody defines body for CreateChatCompletion for application/json ContentType.
type CreateChatCompletionJSONRequestBody = ChatCompletionRequest

// Getter for additional properties for ChatCompletionRequest. Returns the specified
// element and whether it was found
func (a ChatCompletionRequest) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ChatCompletionRequest
func (a *ChatCompletionRequest) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ChatCompletionRequest to handle AdditionalProperties
func (a *ChatCompletionRequest) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["max_tokens"]; found {
		err = json.Unmarshal(raw, &a.MaxTokens)
		if err != nil {
			return fmt.Errorf("error reading 'max_tokens': %w", err)
		}
		delete(object, "max_tokens")
	}

	if raw, found := object["messages"]; found {
		err = json.Unmarshal(raw, &a.Messages)
		if err != nil {
			return fmt.Errorf("error reading 'messages': %w", err)
		}
		delete(object, "messages")
	}

	if raw, found := object["model"]; found {
		err = json.Unmarshal(raw, &a.Model)
		if err != nil {
			return fmt.Errorf("error reading 'model': %w", err)
		}
		delete(object, "model")
	}

	if raw, found := object["stop"]; found {
		err = json.Unmarshal(raw, &a.Stop)
		if err != nil {
			return fmt.Errorf("error reading 'stop': %w", err)
		}
		delete(object, "stop")
	}

	if raw, found := object["stream"]; found {
		err = json.Unmarshal(raw, &a.Stream)
		if err != nil {
			return fmt.Errorf("error reading 'stream': %w", err)
		}
		delete(object, "stream")
	}

	if raw, found := object["temperature"]; found {
		err = json.Unmarshal(raw, &a.Temperature)
		if err != nil {
			return fmt.Errorf("error reading 'temperature': %w", err)
		}
		delete(object, "temperature")
	}

	if raw, found := object["top_p"]; found {
		err = json.Unmarshal(raw, &a.TopP)
		if err != nil {
			return fmt.Errorf("error reading 'top_p': %w", err)
		}
		delete(object, "top_p")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ChatCompletionRequest to handle AdditionalProperties
func (a ChatCompletionRequest) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.MaxTokens != nil {
		object["max_tokens"], err = json.Marshal(a.MaxTokens)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'max_tokens': %w", err)
		}
	}

	if a.Messages != nil {
		object["messages"], err = json.Marshal(a.Messages)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'messages': %w", err)
		}
	}

	object["model"], err = json.Marshal(a.Model)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'model': %w", err)
	}

	if a.Stop != nil {
		object["stop"], err = json.Marshal(a.Stop)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'stop': %w", err)
		}
	}

	if a.Stream != nil {
		object["stream"], err = json.Marshal(a.Stream)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'stream': %w", err)
		}
	}

	if a.Temperature != nil {
		object["temperature"], err = json.Marshal(a.Temperature)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'temperature': %w", err)
		}
	}

	if a.TopP != nil {
		object["top_p"], err = json.Marshal(a.TopP)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'top_p': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Message. Returns the specified
// element and whether it was found
func (a Message) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Message
func (a *Message) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Message to handle AdditionalProperties
func (a *Message) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["content"]; found {
		err = json.Unmarshal(raw, &a.Content)
		if err != nil {
			return fmt.Errorf("error reading 'content': %w", err)
		}
		delete(object, "content")
	}

	if raw, found := object["role"]; found {
		err = json.Unmarshal(raw, &a.Role)
		if err != nil {
			return fmt.Errorf("error reading 'role': %w", err)
		}
		delete(object, "role")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Message to handle AdditionalProperties
func (a Message) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["content"], err = json.Marshal(a.Content)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'content': %w", err)
	}

	object["role"], err = json.Marshal(a.Role)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'role': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Liveness probe (FR-008)
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// Prometheus metrics exposition
	// (GET /metrics)
	GetMetrics(w http.ResponseWriter, r *http.Request)
	// Readiness probe (FR-009)
	// (GET /readyz)
	GetReadyz(w http.ResponseWriter, r *http.Request)
	// Create a chat completion
	// (POST /v1/chat/completions)
	CreateChatCompletion(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMetrics operation middleware
func (siw *ServerInterfaceWrapper) GetMetrics(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMetrics(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadyz operation middleware
func (siw *ServerInterfaceWrapper) GetReadyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateChatCompletion operation middleware
func (siw *ServerInterfaceWrapper) CreateChatCompletion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateChatCompletion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.GetHealthz)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/metrics", wrapper.GetMetrics)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/readyz", wrapper.GetReadyz)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/chat/completions", wrapper.CreateChatCompletion)

	return m
}

type BadGatewayJSONResponse Error

type BadRequestJSONResponse Error

type InternalServerErrorJSONResponse Error

type NotFoundJSONResponse Error

type ServiceUnavailableJSONResponse Error

type TooManyRequestsJSONResponse Error

type UnauthorizedJSONResponse Error

type GetHealthzRequestObject struct {
}

type GetHealthzResponseObject interface {
	VisitGetHealthzResponse(w http.ResponseWriter) error
}

type GetHealthz200JSONResponse HealthStatus

func (response GetHealthz200JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMetricsRequestObject struct {
}

type GetMetricsResponseObject interface {
	VisitGetMetricsResponse(w http.ResponseWriter) error
}

type GetMetrics200TextResponse string

func (response GetMetrics200TextResponse) VisitGetMetricsResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(response))
	return err
}

type GetReadyzRequestObject struct {
}

type GetReadyzResponseObject interface {
	VisitGetReadyzResponse(w http.ResponseWriter) error
}

type GetReadyz200JSONResponse ReadinessStatus

func (response GetReadyz200JSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadyz503JSONResponse ReadinessStatus

func (response GetReadyz503JSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type CreateChatCompletionRequestObject struct {
	Body *CreateChatCompletionJSONRequestBody
}

type CreateChatCompletionResponseObject interface {
	VisitCreateChatCompletionResponse(w http.ResponseWriter) error
}

type CreateChatCompletion200JSONResponse ChatCompletionResponse

func (response CreateChatCompletion200JSONResponse) VisitCreateChatCompletionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateChatCompletion200TexteventStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response CreateChatCompletion200TexteventStreamResponse) VisitCreateChatCompletionResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	flusher, ok := w.(http.Flusher)
	if !ok {
		// If w doesn't support flushing, fall back to io.Copy.
		_, err := io.Copy(w, response.Body)
		return err
	}
	// text/event-stream messages are typically small; use a
	// modest buffer and flush after each chunk so clients see
	// events immediately instead of waiting on OS buffering.
	buf := make([]byte, 4096)
	for {
		n, err := response.Body.Read(buf)
		if n > 0 {
			if _, writeErr := w.Write(buf[:n]); writeErr != nil {
				return writeErr
			}
			flusher.Flush()
		}
		if err != nil {
			if err == io.EOF {
				return nil
			}
			return err
		}
	}
}

type CreateChatCompletion400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateChatCompletion400JSONResponse) VisitCreateChatCompletionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateChatCompletion401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateChatCompletion401JSONResponse) VisitCreateChatCompletionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateChatCompletion404JSONResponse struct{ NotFoundJSONResponse }

func (response CreateChatCompletion404JSONResponse) VisitCreateChatCompletionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateChatCompletion429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response CreateChatCompletion429JSONResponse) VisitCreateChatCompletionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type CreateChatCompletion500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateChatCompletion500JSONResponse) VisitCreateChatCompletionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateChatCompletion502JSONResponse struct{ BadGatewayJSONResponse }

func (response CreateChatCompletion502JSONResponse) VisitCreateChatCompletionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type CreateChatCompletion503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response CreateChatCompletion503JSONResponse) VisitCreateChatCompletionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Liveness probe (FR-008)
	// (GET /healthz)
	GetHealthz(ctx context.Context, request GetHealthzRequestObject) (GetHealthzResponseObject, error)
	// Prometheus metrics exposition
	// (GET /metrics)
	GetMetrics(ctx context.Context, request GetMetricsRequestObject) (GetMetricsResponseObject, error)
	// Readiness probe (FR-009)
	// (GET /readyz)
	GetReadyz(ctx context.Context, request GetReadyzRequestObject) (GetReadyzResponseObject, error)
	// Create a chat completion
	// (POST /v1/chat/completions)
	CreateChatCompletion(ctx context.Context, request CreateChatCompletionRequestObject) (CreateChatCompletionResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealthz operation middleware
func (sh *strictHandler) GetHealthz(w http.ResponseWriter, r *http.Request) {
	var request GetHealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthz(ctx, request.(GetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthzResponseObject); ok {
		if err := validResponse.VisitGetHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMetrics operation middleware
func (sh *strictHandler) GetMetrics(w http.ResponseWriter, r *http.Request) {
	var request GetMetricsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMetrics(ctx, request.(GetMetricsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMetrics")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMetricsResponseObject); ok {
		if err := validResponse.VisitGetMetricsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadyz operation middleware
func (sh *strictHandler) GetReadyz(w http.ResponseWriter, r *http.Request) {
	var request GetReadyzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadyz(ctx, request.(GetReadyzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadyz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadyzResponseObject); ok {
		if err := validResponse.VisitGetReadyzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateChatCompletion operation middleware
func (sh *strictHandler) CreateChatCompletion(w http.ResponseWriter, r *http.Request) {
	var request CreateChatCompletionRequestObject

	var body CreateChatCompletionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateChatCompletion(ctx, request.(CreateChatCompletionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateChatCompletion")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateChatCompletionResponseObject); ok {
		if err := validResponse.VisitCreateChatCompletionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"vFrhctu2k3+VHd59kPKXZMXJ/6Z1PrlJ2uSuiT1xMveh7JgQuRLRgAAPAGWrGc/0Ie4Z7sH6JDe7AClK",
	"omxn/m0+2ZKIxWL3t7u/XfBLkpuqNhq1d8nZl8Siq412yB9+EMVPwuON2NCn3GiP2tO/oq6VzIWXRp/8",
	"5oym71xeYiXov3+3uEzOkn872Yo+Cb+6k9fWGpvc3d1NkgJdbmVNQpKz5GOJ0NTOWxQV1NasZYEWLPrG",
	"aixAaJB6LZQsoFVxltxNSMUP+D8NOv9tVLRhM7gRDiqhlsZWWICxsBRSYQGsIu/K6r3VHq0W6grtGm2Q",
	"/Lfrea6h0XhbY+6xAMdbA9LTYPK8sRYLVu698T+aRhff1HLIDjSNzRFGOFvNoDIFqjFbVBsPS1KJ9SOj",
	"yRw/abEWUomFwm+j6Spgnrwq9BaUBdaoC9T5BqQDtqP2agPNVj9W+6Mx74TeRFi6b6NzriRqD6VwsEDU",
	"YIVHULKSPjr7kxaNL42Vv2Px7UOFHLvdf5bQiiiE9nhZCv/SVLVCWt8LaFEUkr4S6tKaGq2XlJm8bfAA",
	"9GBRKLioUZ+/hexk/fQkL4VnrYNYl3Uqjc5ffZjO509PYf0UXLNw6MczuNBqk+qM8ZhNIKvQObFCR/8H",
	"DNB/HqsarfCNRf5o6uuanxa31958RtpH6CLVmfOmzkBYDBDnLFbA0tgbYQssOmS9AFyj3YDxJVpYSlQF",
	"SJdqkedYeyymi8ZP5UobSwlGCsiGzHIGZJYMRkou0Ao1DcvHs1Qnk6Tume9LstWVPu0a8qIOkqGpa7Sw",
	"oHAEo8ETyjpjgkK98uUsmSR+U2NylkjtcYWWsNYa7lA44cLYAukk5B4opfPGbsgqezuQaOmxcg+B8F3Y",
	"jTaOqghrxYYVIbsPa9GFNT8D3oBtDg4pVkJq53undN5KvSLZ5N17rEc/gyO86RwdeDos6gJWqAk9+wc8",
	"EL9/lKBt2HApGuWTs6VQ7iAO/rtEzUiY8GHaXBaKZuHgRvoSBMH41p/gGrWfRmzD6Orq9TjVC1NswCwh",
	"IwfNeg7Jy0Z/zoAXOfBoK6kFJfTFBrJCeHEGv7y6eP/61yxgLh5hYYxCoflQ29i5z3SiqpXUK+g93nOB",
	"bqpFwBnH3j2CdJMrbNy0E1hbsxALqaTfQCWcG5B6N0koS0hLafKXiKAepH/tVpjFb5h70mM/fQV+cqjY",
	"Xo7as28GQeI2O41nkMmCkkv4pU0suUWye8gtEVCUXTy7HIsVwogybi2cwwJ8aU2zKmFpTdXhfvyCMtTG",
	"eayul1Kv0NZWap9RbTOV9FQ3BjJHXhqZH4vsXuTE52Ak1I3YOMBbkVOxNBrhzz/+F6Qu8Bbm40dH+UsW",
	"OBQZ0RqHKn3S8ha8rNB5UdUwcphTCIzhhmOkFx2LRqpgvC25nCRE7oQPqe0/ng9mOjmw7blmF0y3junZ",
	"RRYTqC0u5S0WkCYEgbyq1TRNBpPMPQks5i3KK7U1RZOzp/cz6IHEiNpDrYOfgko9VB5RrOGU+4DPPoW8",
	"vBdSskg6Nbbem3Sh1kKs3WQ44hgNh6GvEfYOEKE4gz61i6gM7cUuOkd9aO6Cfym1dOW1RRFZ0hDpod/2",
	"6wjxxiLS3ZQrR5pMIE1CEU0T3ks3KpLcwG8ObM6KHYk8PmOMqjbm5hxpOm3m82f4lAJbgDZ6ujJCTeDl",
	"xfvpfP7d+N4S/pCH21zX1eB9X7PKW3GTPRsO+bbrkg6PGTNn6GVQr1GZGiH7AmnC36XJGXyBuNkESPQE",
	"clMg3MFdBs6kutGVKeRSYtFKu3r1Xw5qYV0PHrqAStQ1FtOOJ/AGLtVddp7Ajx+m89P5IMPC9hAP0udX",
	"6IVUB5YLAo7aJ6562EqxpuTCWjqz1E4WSH3N6x0jHoKdzDZUwlxprJ9AJfJSapxaFAWhNm7Hxh5VlFMR",
	"CNGPg3YPbvv7lU0l9Hab3s9EUrjg0c6DWaoWtuVMx7oTfgQ92q0osKiEJ9JmJqFWxA6J9v/6s4UvHnQU",
	"PdaliDjruI5aXkd0U84I/Xz7zXjg3PsUpos9fm4IUm9QKF9eeeGbgdL+s1yjRueYPu2WyF3IuCMCLtbU",
	"kChQraDw4MOqR4FDKr/bIubxTSKVh2h07j6iaWaQxXY4C1myVkJqCErBiICx7RNfpLpqlJeVKYQ6YRYC",
	"cXVYXJi8qVBT4W+zLfSSRpt3U01ZRlIR+i1MagI111HDqStFjQU8n8+JYJMSpdCFQjtL9b0doDOU06au",
	"IdRiAXjrrXARW5kWFWZjoo7bDpMTXuwwJ6CpHQXBOz+mm+yNEgZoSjAxUL8xGKPWqCPhEQYGbZS3vkom",
	"CeqmYngwfWWigDaZJMI56bzQvoeYI8jiXSed6kMI+4CikATXY3HRPbAXGG2PVaOd9oZGAcxUVw4jp3ss",
	"fh6G9ECbuKvR5dCOLyBNzOc0ifOskG1663pe2R7+oVC23dm/MpYnu2cdNvwuqRgGR+vrDmFtaTtGAL8O",
	"t1v5PUlfCeKOU3fC0oQnHQIG1fuXIfvpiL3MZypieW4a7SmlHegwilmRc854BudKrnSbknyJqc6FNlrm",
	"QnXD+RnvNpwQWsG9KdMhx6ytqWp/7yPeeKHueWLPRLsSJwOK7Ik8NOIdE+2lObTiZbNQMoc3Hz9ewvnl",
	"225k5VRD3Pvnn9+1/HGW6lR/LKUDV2Mul3G4SsmeF0i9UghxCE7pzTa+7OTdSItcUazI/ZZvPp10X06X",
	"0jo/nkG4VmDq4DiHcwtrGnYyT+6E3YRUv+1GeQwgffBtZkQtp8TaVqgzWJ/CKHO+mJbe19NANTL4B4Sh",
	"qMvgHzzXtDL37a/jGbwJdcmBJHNT7QvddbdldsVLgrp8J7IUOWahBFaipscdQh0s/OrjBXGvE1aUO6kW",
	"e6nOOvTFKXF2krX5IuPhKC0Q2tOhrG0CUVRig7YtwvPvx9FBcVbiahSfg2uePHnEFJkdFIYDT57sNARb",
	"lkBF+EirQWfO8saqjPpOkuvgxtjPqY7jxhZRgtmENfVU6tC+tqQ1NBCEpydPdgs0K3QfOxifQaM/a3PT",
	"8owwcHbkd0QeNlE1zSZsa3Soc7yuUQvlN/Tj0oaZ5qb/pTIr6a8XUvCsvK2D18FGLErHx6hS0kN//vF/",
	"zEFgh4I4qcKdyh4XyZ7P5+1QUXrFSTLYqO3Yzi/fJpNkjdaFYD2dzWdznneQmrVMzpJns/nsGeUq4UtO",
	"Jicl097f6f8V+qECH8YDp/M5OUMZvaK/BJTampyqHzE+orWUvk0dJ7tvi+Qs+Qn9myh/snutejqf/2U3",
	"MDvM/chFzKGufP3SVJWwm0N+P6K2dv7dmJ86qZBC1x210aU1FfoSG8fVEfC2No7BF0NkBq+2hLjEEDpt",
	"7eF9X6SaTMpzZ+ki+WZhhAltfJh18QUKhcR/Xl28jyEQMHFg+HdR6QcNz1Nw3nDX5PuV+JBpbY8dLQSt",
	"0ocW2LP3wNrtmmB1olebxwGTG9RwgWRxJZ3ny5Xdy8oA9M2EKOA/5894TaqFB4XCeR577S4ozE1MOeyV",
	"MD1wB5w21VtSS+dfGF9CLhy6I475EM71NwbEPmsfuh9XCvoklPNQNBHflf5z/uyb6vOAH/bgs992hHj9",
	"PsbrQMUiFWvjhnDUaBcJ88C1Fye6vXsyhyo0q4tNJAUZF1O+dmpvSUnzjG+nstA9xyur8d6VVACxiIQo",
	"1RzY2fBtSgaj0/l8fGSz0Pjec+GV6uEbL2Yk0yuiLK/5Xmsc85B2HkXRNp+kWarbzh4WqMzNLBTQy7fw",
	"bDYnjsJvLzRKbSicLTlIaLi6et01hhOeQBqtQjuvjY6aEF1zTc5Zmik4HapLepQ0X/AKEkbsI9ULLMVa",
	"msbSkx3timXUh/cspIaX5x9eTefz50Ph+JIn77vWTgKfRud/MMVf99bP8P3+3S59Jx/e/Y2Z4cgt3R3f",
	"S+5BY1fqbtAcYgZiiJhlP4oKVF44GLU+GBzVDb/MsRuPM/jR2BbvZzGu+hVTRHweC51dAdtY6dYfi46r",
	"1+PuDhtGDhE6CPUnCC9SvT1kyje9z4PjhvzROfik9/IWL3n68JKd11h40fOHF3UvOtGC0+8fXrD/Cg/X",
	"hEccaOh1L157+ihjtC/bbUvQ/UsGXpDaLRUhxA8zfABeaOBccvbLl3vegmJqgg6YNofRuFwjeAPSO1BE",
	"ODSIoqCERwhvrErOkpPk7te7/w8AAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
